# Site
title:              David Patiño
bio:                'Psicólogo Cognitivo-conductual <br> Psicoterapia basada en la evidencia en <br> @psico.logia.co'
description:        "Psico.logia es un proyecto de divulgación y atención en psicología"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://psico-logia.github.io/Homepage

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   Psico logia

# Social
# if you don't have any of social below, comment the line.
#google:
 #plus:            #username
 #analytics:
 #verify:
 #ad-client:
 #ad-slot:
#bing-verify:
email:              davida.psicologia@gmail.com
#twitter:            username
facebook:           Psico.logia.david
github-url:         Psico-Logia
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          david-psico-logia
#xing:              username
instagram:          psico.logia.co
#lastfm:            username
#tumblr:            @psico.logia
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:            psicologia0
youtube-channel:   psicologia0
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]

theme: jekyll-theme-minimal